### ISSUE TITLE
Difference between Envoy url and simple url ?

### ISSUE THREAD

**Issue by KhurramShahzad094** [greatfire/envoy#3]
what is envoy url and simple url?
And what is the difference between them ?

**Comment by greatfire-martin** [comment]
In its simplest form, an envoy URL is just an HTTP(s) URL, such as "https://allowed.example.com/app1/". But envoy also accepts a special URL scheme in this form: "envoy://k1=v1[&kn=vn]?" which includes more parameters.

This is documented further here: https://github.com/greatfire/envoy/tree/master/native#examples
